version: '2'
services:
  db:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: foodscout
      MYSQL_DATABASE: foodscout
      MYSQL_USER: foodscout
      MYSQL_PASSWORD: foodscout
  api:
    depends_on:
      - db
    build: ../..
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
      - "./config:/usr/src/app/config"
  web:
    image: registry.foodscoutdomain.de/food-frontend
    ports:
      - 80:80