version: '2'
services:
  db:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: foodscout
      MYSQL_DATABASE: foodscout
      MYSQL_USER: foodscout
      MYSQL_PASSWORD: foodscout
      LANG: C.UTF-8
    ports:
    - 3306:3306
    volumes:
    - "./import:/docker-entrypoint-initdb.d"
    restart: always
  api:
    depends_on:
      - db
    build: ../..
    links:
      - db
    ports:
      - 8080:8080
    volumes:
      - "./config:/usr/src/app/config"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: foodscout_phpmyadmin
    ports:
    - 80:80
    links:
    - db
